"""
Seed lexicon: ~420 common Gujlish words with rough frequency weights.

This is HAND-BUILT and is a stand-in, not the real thing. It exists so
the prototype has something to suggest today. build_lexicon.py replaces
it with corpus-derived data (Gujarati Wikipedia frequencies joined to
Dakshina + Aksharantar romanisations).

Frequency is a rough 1-100 commonness weight, not a corpus count.
Gloss is only for review — it never ships to the device.
"""

# (surface, freq, gloss)
WORDS = [
    # ---- copula / existence: the highest-frequency words in the language
    ("che", 100, "is / are"),
    ("chu", 95, "I am"),
    ("cho", 90, "you are (formal)"),
    ("chie", 78, "we are"),
    ("nathi", 92, "is not"),
    ("hatu", 80, "was"),
    ("hata", 72, "were"),
    ("hati", 70, "was (f)"),
    ("hase", 68, "will be"),
    ("hoy", 66, "may be"),
    ("thai", 74, "become / happen"),
    ("thayu", 88, "happened / done"),
    ("thay", 76, "happens"),
    ("thashe", 82, "will happen"),
    ("thavu", 62, "to become"),
    ("thato", 48, "becoming"),

    # ---- pronouns
    ("hu", 96, "I"),
    ("tu", 85, "you (informal)"),
    ("tame", 90, "you (formal)"),
    ("ame", 74, "we"),
    ("apne", 72, "we / us"),
    ("mane", 90, "to me"),
    ("tane", 78, "to you"),
    ("tamne", 82, "to you (formal)"),
    ("amne", 64, "to us"),
    ("ene", 70, "to him/her"),
    ("teni", 58, "his/her"),
    ("maru", 80, "my"),
    ("mara", 76, "my (pl)"),
    ("taru", 68, "your"),
    ("tamaru", 70, "your (formal)"),
    ("amaru", 58, "our"),
    ("potana", 44, "one's own"),
    ("badha", 74, "everyone / all"),
    ("badhu", 76, "everything"),
    ("koi", 72, "someone / any"),
    ("kai", 80, "something / anything"),

    # ---- question words
    ("kem", 95, "how / why"),
    ("su", 94, "what"),
    ("kyare", 78, "when"),
    ("kya", 84, "where"),
    ("kon", 74, "who"),
    ("kone", 62, "by whom"),
    ("kevu", 70, "how / what kind"),
    ("kevi", 64, "how (f)"),
    ("ketlu", 72, "how much"),
    ("ketla", 68, "how many"),
    ("kayu", 60, "which"),
    ("kayo", 56, "which (m)"),
    ("shene", 40, "why / for what"),

    # ---- greetings and stock replies
    ("majama", 88, "fine / well"),
    ("maja", 80, "fun / wellbeing"),
    ("saras", 84, "excellent"),
    ("saru", 86, "good"),
    ("sara", 70, "good (pl)"),
    ("sari", 66, "good (f)"),
    ("barabar", 76, "correct / alright"),
    ("thik", 82, "okay / fine"),
    ("kharab", 60, "bad"),
    ("aavjo", 78, "goodbye"),
    ("aavo", 70, "come / welcome"),
    ("abhar", 64, "thanks"),
    ("dhanyavad", 58, "thank you"),
    ("maaf", 54, "forgive / sorry"),
    ("jsk", 52, "Jai Shree Krishna"),
    ("ram", 44, "Ram (greeting)"),

    # ---- yes / no / agreement
    ("ha", 92, "yes"),
    ("na", 90, "no"),
    ("nahi", 88, "not / no"),
    ("nai", 74, "not (colloquial)"),
    ("bilkul", 66, "absolutely"),
    ("kharekhar", 54, "really"),
    ("sacchu", 68, "true"),
    ("khoto", 48, "false"),
    ("chokkas", 56, "certainly"),

    # ---- high-frequency verbs
    ("karu", 82, "I do"),
    ("kare", 80, "does"),
    ("karo", 78, "do (imperative)"),
    ("karyu", 76, "did"),
    ("karse", 66, "will do"),
    ("karva", 70, "to do"),
    ("karta", 58, "while doing"),
    ("jau", 80, "I go"),
    ("jay", 74, "goes"),
    ("jao", 72, "go"),
    ("gayo", 74, "went (m)"),
    ("gayi", 66, "went (f)"),
    ("gaya", 64, "went (pl)"),
    ("jaish", 68, "will go"),
    ("java", 62, "to go"),
    ("avu", 78, "I come"),
    ("ave", 76, "comes"),
    ("avyo", 70, "came (m)"),
    ("avi", 68, "came (f)"),
    ("avse", 66, "will come"),
    ("avva", 54, "to come"),
    ("kahu", 66, "I say"),
    ("kahe", 68, "says"),
    ("kaho", 62, "say / tell me"),
    ("kahyu", 64, "said"),
    ("kidhu", 72, "said / did"),
    ("bolu", 58, "I speak"),
    ("bole", 56, "speaks"),
    ("bolo", 60, "speak"),
    ("bolyo", 52, "spoke"),
    ("jou", 66, "I see / want"),
    ("joi", 64, "seen / needed"),
    ("joye", 70, "is needed"),
    ("joyu", 62, "saw"),
    ("joto", 46, "looking"),
    ("samju", 56, "I understand"),
    ("samje", 54, "understands"),
    ("samjyu", 64, "understood"),
    ("khavu", 66, "to eat"),
    ("khau", 60, "I eat"),
    ("khay", 56, "eats"),
    ("khadhu", 62, "ate"),
    ("piu", 48, "I drink"),
    ("pise", 44, "will drink"),
    ("apo", 70, "give"),
    ("apu", 62, "I give"),
    ("apyu", 58, "gave"),
    ("lidhu", 62, "took"),
    ("levu", 58, "to take"),
    ("lav", 60, "bring"),
    ("lavo", 56, "bring (formal)"),
    ("mokal", 58, "send"),
    ("mokalyu", 54, "sent"),
    ("malyo", 62, "met (m)"),
    ("mali", 56, "met / received"),
    ("malse", 58, "will meet"),
    ("malva", 54, "to meet"),
    ("betho", 54, "sat"),
    ("beso", 52, "sit"),
    ("ubho", 44, "standing"),
    ("sui", 50, "sleep"),
    ("sut", 42, "asleep"),
    ("rahe", 62, "stays / lives"),
    ("raho", 58, "stay"),
    ("rahyo", 60, "staying (m)"),
    ("rahi", 56, "staying (f)"),
    ("puchyu", 52, "asked"),
    ("puch", 50, "ask"),
    ("jane", 54, "knows"),
    ("janu", 48, "I know"),
    ("mukyu", 46, "placed"),
    ("muk", 48, "put"),
    ("vat", 76, "talk / matter"),
    ("vato", 62, "talks"),
    ("lage", 74, "feels / seems"),
    ("lagyu", 58, "felt"),
    ("gamyu", 60, "liked"),
    ("game", 64, "likes"),
    ("pidhu", 40, "drank"),
    ("vaparu", 36, "I use"),
    ("sikhu", 42, "I learn"),
    ("sikhyu", 44, "learned"),

    # ---- knowing / not knowing
    ("khabar", 82, "news / knowledge"),
    ("yad", 66, "memory / remember"),
    ("bhulyo", 48, "forgot"),
    ("bhul", 52, "mistake"),

    # ---- time
    ("aaje", 84, "today"),
    ("kale", 82, "tomorrow / yesterday"),
    ("have", 86, "now"),
    ("pachhi", 78, "later / after"),
    ("pehla", 68, "before / first"),
    ("roj", 64, "daily"),
    ("savare", 66, "in the morning"),
    ("bapore", 58, "in the afternoon"),
    ("sanje", 62, "in the evening"),
    ("ratre", 64, "at night"),
    ("vakhat", 62, "time"),
    ("samay", 58, "time"),
    ("vagya", 66, "o'clock"),
    ("divas", 64, "day"),
    ("varas", 54, "year"),
    ("mahino", 52, "month"),
    ("aathvadiyu", 40, "week"),
    ("turant", 48, "immediately"),
    ("jaldi", 70, "quickly / soon"),
    ("modu", 56, "late"),
    ("hamna", 58, "just now"),
    ("kayam", 44, "always"),
    ("kadi", 42, "ever"),

    # ---- places
    ("ghar", 80, "home"),
    ("ghare", 82, "at home"),
    ("bahar", 70, "outside"),
    ("andar", 62, "inside"),
    ("aiya", 68, "here"),
    ("tya", 72, "there"),
    ("office", 74, "office"),
    ("bajar", 58, "market"),
    ("dukan", 52, "shop"),
    ("gam", 56, "village"),
    ("saher", 50, "city"),
    ("desh", 46, "country"),
    ("rasto", 48, "road"),
    ("station", 46, "station"),
    ("school", 54, "school"),
    ("kolej", 48, "college"),
    ("mandir", 52, "temple"),
    ("hospital", 44, "hospital"),

    # ---- family and people
    ("bhai", 84, "brother"),
    ("ben", 76, "sister"),
    ("mummy", 72, "mother"),
    ("pappa", 72, "father"),
    ("ba", 58, "mother / grandma"),
    ("bapuji", 44, "father"),
    ("kaka", 60, "uncle (paternal)"),
    ("kaki", 52, "aunt"),
    ("mama", 58, "uncle (maternal)"),
    ("mami", 50, "aunt"),
    ("foi", 48, "aunt (paternal)"),
    ("fua", 42, "uncle"),
    ("dada", 54, "grandfather"),
    ("dadi", 52, "grandmother"),
    ("nana", 48, "grandfather (m)"),
    ("nani", 46, "grandmother (m)"),
    ("dikro", 60, "son"),
    ("dikri", 58, "daughter"),
    ("chokro", 56, "boy"),
    ("chokri", 52, "girl"),
    ("baiko", 48, "wife"),
    ("patni", 40, "wife"),
    ("mitra", 50, "friend"),
    ("dost", 62, "friend"),
    ("parivar", 48, "family"),
    ("loko", 60, "people"),
    ("manas", 52, "person"),

    # ---- food
    ("jaman", 66, "meal"),
    ("jamva", 70, "to eat (meal)"),
    ("jamyo", 58, "ate (m)"),
    ("khavana", 52, "food"),
    ("pani", 72, "water"),
    ("cha", 70, "tea"),
    ("dudh", 56, "milk"),
    ("rotli", 58, "flatbread"),
    ("roti", 52, "bread"),
    ("shaak", 60, "vegetable dish"),
    ("dal", 58, "lentils"),
    ("bhat", 56, "rice"),
    ("khichdi", 50, "khichdi"),
    ("thepla", 48, "thepla"),
    ("dhokla", 50, "dhokla"),
    ("fafda", 46, "fafda"),
    ("jalebi", 44, "jalebi"),
    ("mithai", 44, "sweets"),
    ("nasto", 50, "snack"),
    ("bhakhri", 40, "bhakhri"),
    ("kadhi", 42, "kadhi"),
    ("athanu", 36, "pickle"),
    ("mithu", 40, "salt / sweet"),
    ("tikhu", 42, "spicy"),
    ("garam", 54, "hot"),
    ("thandu", 50, "cold"),

    # ---- work and money
    ("kaam", 84, "work"),
    ("nokri", 62, "job"),
    ("paisa", 74, "money"),
    ("rupiya", 56, "rupees"),
    ("bill", 48, "bill"),
    ("kharch", 46, "expense"),
    ("pagar", 44, "salary"),
    ("dhandho", 42, "business"),
    ("gadi", 62, "car / vehicle"),
    ("phone", 66, "phone"),
    ("message", 58, "message"),
    ("meeting", 56, "meeting"),
    ("project", 50, "project"),
    ("computer", 42, "computer"),

    # ---- descriptors
    ("moto", 66, "big (m)"),
    ("mota", 60, "big (pl)"),
    ("nano", 60, "small (m)"),
    ("nanu", 58, "small"),
    ("ghanu", 72, "a lot"),
    ("ghana", 64, "many"),
    ("thodu", 70, "a little"),
    ("thoda", 60, "a few"),
    ("jhaju", 58, "too much"),
    ("puru", 56, "complete"),
    ("navu", 58, "new"),
    ("junu", 50, "old"),
    ("sachu", 54, "true"),
    ("sarkhu", 48, "same / proper"),
    ("alag", 46, "different"),
    ("aakhu", 48, "whole"),
    ("sunder", 40, "beautiful"),
    ("mushkel", 44, "difficult"),
    ("saral", 38, "easy"),
    ("khush", 58, "happy"),
    ("dukhi", 40, "sad"),
    ("thakelo", 42, "tired"),
    ("bimar", 44, "unwell"),
    ("majboot", 34, "strong"),
    ("khali", 48, "empty / only"),
    ("bharelu", 32, "full"),

    # ---- connectives and particles: invisible but constant
    ("ane", 88, "and"),
    ("pan", 86, "also / but"),
    ("ke", 84, "that / or"),
    ("ne", 82, "to / isn't it"),
    ("etle", 76, "so / therefore"),
    ("karan", 62, "reason / because"),
    ("matlab", 70, "meaning / so"),
    ("mate", 74, "for"),
    ("thi", 68, "from"),
    ("sudhi", 60, "until"),
    ("sathe", 72, "with"),
    ("vagar", 52, "without"),
    ("jem", 56, "as / like"),
    ("tem", 48, "so / thus"),
    ("jyare", 58, "when"),
    ("tyare", 56, "then"),
    ("agar", 44, "if"),
    ("to", 82, "then"),
    ("bas", 74, "enough / just"),
    ("fakt", 62, "only"),
    ("hji", 58, "still / yet"),
    ("have to", 44, "now then"),
    ("kharu", 52, "right / true"),
    ("chalo", 72, "let's go / alright"),
    ("jo", 66, "look / if"),
    ("are", 68, "hey"),
    ("arre", 60, "hey / oh"),
    ("haju", 62, "still"),
    ("pela", 50, "that one"),
    ("aa", 84, "this"),
    ("te", 66, "that"),
    ("eva", 48, "such"),
    ("evu", 58, "such / like that"),
    ("kharekhar", 46, "truly"),

    # ---- common short phrases stored as single units
    ("kemcho", 70, "how are you"),
    ("majama", 88, "fine"),
    ("suchalerahyuche", 20, "what's going on"),

    # ---- misc high-use
    ("problem", 56, "problem"),
    ("tension", 54, "worry"),
    ("chinta", 44, "worry"),
    ("madad", 46, "help"),
    ("jarur", 58, "need / certainly"),
    ("jaruri", 50, "necessary"),
    ("taiyar", 56, "ready"),
    ("suru", 62, "start"),
    ("puro", 52, "finish"),
    ("band", 54, "closed"),
    ("chalu", 56, "running / on"),
    ("photo", 50, "photo"),
    ("naam", 68, "name"),
    ("umar", 42, "age"),
    ("rasta", 40, "roads"),
    ("mosam", 38, "weather"),
    ("varsad", 44, "rain"),
    ("tabiyat", 46, "health"),
    ("dawa", 40, "medicine"),
    ("hava", 36, "air"),
    ("sapnu", 32, "dream"),
    ("kism", 26, "kind"),
]

# (previous_word, next_word, weight) — what actually follows what.
# This is where the "predict the next letter" feeling comes from.
BIGRAMS = [
    ("kem", "cho", 100), ("kem", "che", 90), ("kem", "thayu", 70),
    ("kem", "nahi", 55), ("kem", "chu", 40),
    ("su", "karo", 95), ("su", "kare", 80), ("su", "thayu", 90),
    ("su", "che", 85), ("su", "chale", 60), ("su", "kahe", 50),
    ("su", "vat", 55), ("su", "naam", 40),
    ("majama", "chu", 95), ("majama", "che", 70), ("majama", "cho", 50),
    ("thayu", "che", 95), ("thayu", "hatu", 60), ("thayu", "ke", 45),
    ("khabar", "nathi", 95), ("khabar", "che", 80), ("khabar", "padi", 50),
    ("mane", "khabar", 85), ("mane", "lage", 90), ("mane", "game", 70),
    ("mane", "joye", 75), ("mane", "apo", 50), ("mane", "kaho", 45),
    ("hu", "avu", 85), ("hu", "jau", 80), ("hu", "chu", 90),
    ("hu", "karu", 70), ("hu", "aviyo", 40), ("hu", "ghare", 55),
    ("tame", "kem", 90), ("tame", "su", 85), ("tame", "kya", 75),
    ("tame", "cho", 80), ("tame", "avo", 55), ("tame", "kaho", 45),
    ("kya", "cho", 90), ("kya", "che", 85), ("kya", "jao", 70),
    ("kya", "gayo", 65), ("kya", "thi", 55),
    ("ghare", "avo", 80), ("ghare", "ja", 65), ("ghare", "chu", 70),
    ("ghare", "pahochyo", 45),
    ("jaman", "thayu", 85), ("jaman", "karyu", 60),
    ("kai", "nathi", 95), ("kai", "vandho", 55), ("kai", "kaam", 45),
    ("thik", "che", 98), ("saru", "che", 90), ("saras", "che", 80),
    ("barabar", "che", 85),
    ("badhu", "saru", 75), ("badhu", "thik", 80), ("badhu", "puru", 55),
    ("ketla", "vagya", 90), ("ketlu", "thayu", 60),
    ("kaam", "che", 80), ("kaam", "karu", 70), ("kaam", "puru", 60),
    ("aaje", "su", 80), ("aaje", "avo", 60), ("aaje", "kaam", 55),
    ("kale", "malse", 70), ("kale", "avu", 65), ("kale", "javu", 55),
    ("have", "su", 85), ("have", "thayu", 60), ("have", "jau", 55),
    ("nathi", "khabar", 50), ("nathi", "thayu", 45),
    ("jai", "rahyo", 80), ("jai", "shree", 70),
    ("phone", "karu", 80), ("phone", "kar", 70),
    ("vat", "karu", 80), ("vat", "thai", 65), ("vat", "che", 60),
    ("paisa", "aapya", 55), ("paisa", "joye", 60),
    ("chalo", "jaiye", 75), ("chalo", "pachhi", 55),
    ("bhai", "kem", 70), ("ben", "kem", 60),
    ("bahu", "saru", 70), ("ghanu", "saru", 65),
]
